apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: gcr.io/cloud-chef-439008/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"

---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  namespace: gcp-todo-prod
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: backend
  type: LoadBalancer
