apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: gcr.io/cloud-chef-439008/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: gcp-todo-prod
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: frontend
  type: LoadBalancer
